name: silo-v2
networks:
- id: 42161
  start_block: 0
  contracts:
  - name: SiloFactory
    address:
    - 0xf7dc975C96B434D436b9bF45E7a45c95F0521442
    handler: src/EventHandlers.ts
    events:
    - event: NewSilo(address indexed implementation, address indexed token0, address indexed token1, address silo0, address silo1, address siloConfig)
  - name: Silo
    address:
    - 0x2a3B686dEC8DeD90aEd1aEC9dCf289DbF82C7973
    - 0x2691aDFAaD4A34502c2Be4AAb6C26bF4497EB582
    - 0x3c91d761920bD6063606CE478FE8E39e61c3f2C4
    - 0x7ae9788d79a15B8897fF3F9e85f8885B0c4F93df
    - 0x584D5b1A086F8F6F6607C1902424ed16FA5d5843
    - 0xED586ca4F7a6f3924730934144d39a16E6643D35
    - 0xae91CD64041E1Bd4f4954254E146faCbf7CB9a77
    - 0x5e5540930ef576C5044Af00056e85327600ab305
    - 0x7b54D87C877A10CD0b06De61D7CC17210D8c52ec
    - 0x593aFB8331835f897ECE3f415Bcb6F325D837bb8
    handler: src/EventHandlers.ts
    events:
    - event: Approval(address indexed owner, address indexed spender, uint256 value)
    - event: Borrow(address indexed sender, address indexed receiver, address indexed owner, uint256 assets, uint256 shares)
    - event: CollateralTypeChanged(address indexed borrower)
    - event: Deposit(address indexed sender, address indexed owner, uint256 assets, uint256 shares)
    - event: DepositProtected(address indexed sender, address indexed owner, uint256 assets, uint256 shares)
    - event: FlashLoan(uint256 amount)
    - event: HooksUpdated(uint24 hooksBefore, uint24 hooksAfter)
    - event: Initialized(uint64 version)
    - event: Transfer(address indexed from, address indexed to, uint256 value)
    - event: Withdraw(address indexed sender, address indexed receiver, address indexed owner, uint256 assets, uint256 shares)
    - event: WithdrawProtected(address indexed sender, address indexed receiver, address indexed owner, uint256 assets, uint256 shares)
    - event: WithdrawnFeed(uint256 daoFees, uint256 deployerFees)
  - name: Token
    address: 
    - 0x0341C0C0ec423328621788d4854119B97f44E391
    handler: src/EventHandlers.ts
    events:
    - event: Approval(address indexed owner, address indexed spender, uint256 value)
    - event: DelegateChanged(address indexed delegator, address indexed fromDelegate, address indexed toDelegate)
    - event: DelegateVotesChanged(address indexed delegate, uint256 previousBalance, uint256 newBalance)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: Transfer(address indexed from, address indexed to, uint256 value)
- id: 146
  start_block: 2550467
  rpc_config: 
    url: "https://sonic.drpc.org"
  contracts:
  - name: SonicSiloFactory
    address:
    - 0xa42001D6d2237d2c74108FE360403C4b796B7170
    handler: src/EventHandlers.ts
    events:
    - event: NewSilo(address indexed implementation, address indexed token0, address indexed token1, address silo0, address silo1, address siloConfig)
  - name: SonicSilo
    address:
    - 0xBfF04857353cc593F85C40a1d47342d3E3633115
    - 0xE61527810F6DAdf21a8Ed4eE7C884cC977611f0F
    - 0x0F0d1CFB37C310E2dE33Dc2C23849Bf24014fAea
    - 0x164832d4B539709aDF6dF94D5FC2EdDbA82af899
    - 0x396922EF30Cf012973343f7174db850c7D265278
    - 0x47d8490Be37ADC7Af053322d6d779153689E13C1
    - 0x8F0694db47D8BcBE74DDBb43c8cBe0bC0c2Daa40
    - 0xE179AF0Bae65738ed5766Aa70d6b8a45553D0a3A
    - 0x5F06F5d205c1f81417cc5a554a34F46C47a1e37F
    - 0x7d09707fd06792D3aEcB9A3feB509C05D5fE6405
    - 0xEc56fD815C6d603DF0C77038c8EeFfD2cA3B8A6F
    - 0xbC0e4a000666A893928454e4c587c28fe6de6CE5
    - 0x364C72c6fB022522ef490ecC5e945f6aFe47aF95
    - 0x2B421676bE0d42E9975f3E364932c8C1Bc498805
    - 0xE223C8e92AA91e966CA31d5C6590fF7167E25801
    - 0x4E216C15697C1392fE59e1014B009505E05810Df
    - 0x4bFead9975A64545C3594090327ef6666C2f6164
    - 0x427514a905fa6bEaed9A36E308Fcfa06cE54e95b
    - 0x91112b1C5779b6668E61Aa776862781232aDd587
    - 0xBc7787ed47b2912E822407b695948dE4A2D4619D
    - 0xD8E21d3CB790aF3E31C4F42313694F45A5DabeCD
    - 0x913a34DE91347EbABa0433d6dA41e775004585C4
    - 0x34bb955F10f01E05d2639a12a9FbF770853eAC4b
    - 0x9eD5a9c8F09AA245f105B23B1EE27723c4AD8D69


  
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(address indexed sender, address indexed owner, uint256 assets, uint256 shares)
    - event: Withdraw(address indexed sender, address indexed receiver, address indexed owner, uint256 assets, uint256 shares)
    - event: Transfer(address indexed from, address indexed to, uint256 value)
    - event: HooksUpdated(uint24 hooksBefore, uint24 hooksAfter)
    - event: Initialized(uint64 version)
raw_events: true